name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:

      # Checkout del Repositorio
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      # Escaneo de SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      # Verificación del Quality Gate
      - name: Get Quality Gate Status
        id: quality_gate
        run: |
          projectKey="Angel07fco_proyecto-jireh"
          apiUrl="https://sonarcloud.io/api/qualitygates/project_status?projectKey=${projectKey}"
          quality_gate_status=$(curl -s "$apiUrl" | jq -r '.projectStatus.status')
          echo "::set-output name=status::$quality_gate_status"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Si es necesario, proporciona un token de autenticación

      #Verficación del estado
      - name: Check Quality Gate Status
        run: |
          status="${{ steps.quality_gate.outputs.status }}"
          if [ "$status" = "ERROR" ]; then
            echo "Quality Gate check failed."
            git reset --hard HEAD^  
            exit 1
          else
            echo "Quality Gate passed."
          fi